// MCity Dashboard V2 - Friends UI (phase 3.1).
import { ActionFormData, ModalFormData, MessageFormData } from "@minecraft/server-ui";
import { UI } from "../../core/uiTheme.js";
import { PlayerRegistry } from "../../core/playerRegistry.js";
import { FriendService } from "./friendService.js";
import { CONFIG } from "../../config.js";
export class FriendUI{
 static async open(player){const req=FriendService.requests(player), friends=FriendService.list(player);const form=new ActionFormData().title(UI.title(UI.ICON.profile,"Friends")).body(UI.body(`§7Friends: §f${friends.length}`,`§7Incoming requests: §e${req.incoming.length}`)).button("§aMy Friends").button(`§eRequests (${req.incoming.length})`).button("§bSend Friend Request").button(UI.BACK);const r=await form.show(player);if(r.canceled||r.selection===3)return; if(r.selection===0)return this.list(player);if(r.selection===1)return this.requests(player);if(r.selection===2)return this.send(player);}
 static async list(player){const friends=FriendService.list(player);const form=new ActionFormData().title(UI.title(UI.ICON.profile,"My Friends")).body(UI.body(`§7Friends: §f${friends.length}`));for(const f of friends)form.button(f.playerName);form.button(UI.BACK);const r=await form.show(player);if(r.canceled||r.selection>=friends.length)return this.open(player);return this.friendDetails(player,friends[r.selection]);}
 static async friendDetails(player,friend){const r=await new ActionFormData().title(UI.title(UI.ICON.profile,friend.playerName)).body(UI.body("§7Friend")).button("§bSend Message").button("§fReceived Messages").button("§aSend Money").button("§dSend Gift").button("§eRemove Friend").button(UI.BACK).show(player);if(r.canceled||r.selection===5)return this.list(player);if(r.selection===0)return this.sendMessage(player,friend);if(r.selection===1)return this.messages(player);if(r.selection===2)return this.sendMoney(player,friend);if(r.selection===3)return this.sendGift(player,friend);if(r.selection===4){const c=await new MessageFormData().title("Remove Friend").body(`Remove ${friend.playerName}?`).button1("Cancel").button2("Remove").show(player);if(!c.canceled&&c.selection===1){const res=FriendService.remove(player,friend.playerId);player.sendMessage(CONFIG.PREFIX+res.message);}return this.list(player);}}
 static async requests(player){const req=FriendService.requests(player).incoming;const form=new ActionFormData().title(UI.title(UI.ICON.profile,"Friend Requests")).body(UI.body(`§7Incoming: §f${req.length}`));for(const r of req)form.button(r.playerName);form.button(UI.BACK);const r=await form.show(player);if(r.canceled||r.selection>=req.length)return this.open(player);return this.respond(player,req[r.selection]);}
 static async respond(player,request){const r=await new ActionFormData().title(UI.title(UI.ICON.profile,request.playerName)).body(UI.body("§7Friend request")).button("§aAccept").button("§cReject").show(player);if(r.canceled)return this.requests(player);const res=FriendService.respond(player,request.playerId,r.selection===0);player.sendMessage(CONFIG.PREFIX+res.message);return this.requests(player);}
 static async sendMessage(player,friend){const r=await new ModalFormData().title(`Message ${friend.playerName}`).textField("Message","Write a message",{defaultValue:""}).show(player);if(r.canceled)return this.friendDetails(player,friend);const res=FriendService.sendMessage(player,friend.playerId,r.formValues?.[0]);player.sendMessage(CONFIG.PREFIX+res.message);return this.friendDetails(player,friend);}
 static async sendMoney(player,friend){const target=PlayerRegistry.findOnlineById(friend.playerId);if(!target){player.sendMessage(CONFIG.PREFIX+"§eFriend must be online to receive a direct transfer.");return this.friendDetails(player,friend);}const r=await new ModalFormData().title(`Send Money to ${friend.playerName}`).textField("Amount ($)","10.00",{defaultValue:"10.00"}).show(player);if(r.canceled)return this.friendDetails(player,friend);const raw=Number(r.formValues?.[0]);const cents=Number.isFinite(raw)?Math.round(raw*100):0;const res=FriendService.sendMoney(player,target,cents);player.sendMessage(CONFIG.PREFIX+res.message);return this.friendDetails(player,friend);}
 static async sendGift(player,friend){const allowed=CONFIG.FRIENDS?.ALLOWED_GIFT_ITEMS||[];if(!allowed.length){player.sendMessage(CONFIG.PREFIX+"§eFriend gifts are not configured yet.");return this.friendDetails(player,friend);}const form=new ActionFormData().title(`Send Gift to ${friend.playerName}`).body(UI.body("§7Select one allowed item."));for(const id of allowed)form.button(id);form.button(UI.BACK);const r=await form.show(player);if(r.canceled||r.selection>=allowed.length)return this.friendDetails(player,friend);const res=FriendService.sendGift(player,friend.playerId,allowed[r.selection]);player.sendMessage(CONFIG.PREFIX+res.message);return this.friendDetails(player,friend);}
 static async messages(player){const list=FriendService.messages(player);const form=new ActionFormData().title(UI.title(UI.ICON.notification,"Received Messages")).body(UI.body(`§7Messages: §f${list.length}`));for(const m of list)form.button(`${m.read?"§f":"§e"}${m.senderName}\n§8${new Date(m.createdAt).toLocaleString()}`);form.button(UI.BACK);const r=await form.show(player);if(r.canceled||r.selection>=list.length)return this.open(player);const m=list[r.selection];const view=await new ActionFormData().title(UI.title(UI.ICON.notification,`Message from ${m.senderName}`)).body(UI.body(m.body)).button("§aMark Read").button(UI.BACK).show(player);if(!view.canceled&&view.selection===0)FriendService.markMessageRead(player,m.id);return this.messages(player);}
 static async send(player){const online=PlayerRegistry.online().filter(p=>p.id!==player.id);const form=new ActionFormData().title(UI.title(UI.ICON.profile,"Send Friend Request")).body(UI.body(`§7Online players: §f${online.length}`));for(const p of online)form.button(p.name);form.button(UI.BACK);const r=await form.show(player);if(r.canceled||r.selection>=online.length)return this.open(player);const res=FriendService.sendRequest(player,online[r.selection]);player.sendMessage(CONFIG.PREFIX+res.message);return this.open(player);}
}
export default FriendUI;
